config/routes.rb
MyfirstApp::Application.routes.draw do
  resources :purchases
  resources :users
  resources :tasklists
  get "landing_pages/home"
  get "welcome/index"

  root 'landing_pages#home'
  

  

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
  end

  def index
  end
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  def new
    @task_list = Tasklist.new
  end
  
  def index
    @task_lists = Tasklist.all
  end
  
  def create
    @task_list = Tasklist.new(tasklist_params)
    if @task_list.save
      redirect_to tasklists_path
    else
      render 'new'
    end
  end
  
  def edit
    @task_list = Tasklist.find(params[:id])
  end
  
  def update
    @task_list = Tasklist.find(params[:id])
    if @task_list.update_attributes(params[:task_list])
      redirect_to tasklists_path(@task_list.id)
    else
      render 'edit'
    end
  end
  
  def destroy
    @task_list = Tasklist.find(params[:id])
    @task_list.destroy
    redirect_to tasklists_path
  end
  
  def show
    @task_list = Tasklist.find(params[:id])
  end
  
  private
  
  def tasklist_params
    params.require(:task_list).permit(:title, :name)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
  end

  def index
    @users=User.all
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
 	end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/landing_pages/home.html.erb
<h1>LandingPages#home</h1>
<p>Find me in app/views/landing_pages/home.html.erb</p>

<a href='users/'>Users</a><br>
<a href='users/new'>Create new user</a>
<br><br>
<a href='tasklists/'>Tasklists</a><br>
<a href='tasklists/new'>Create new tasklist</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyfirstApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/purchases/index.html.erb
<h1>Purchases#index</h1>
<p>Find me in app/views/purchases/index.html.erb</p>

app/views/purchases/new.html.erb
<h1>Purchases#new</h1>
<p>Find me in app/views/purchases/new.html.erb</p>

app/views/tasklists/edit.html.erb
<%= form_for(@task_list) do |f| %>
  <div class="field">
    <p>title</p>
    <%= f.text_field :title%>
  </div>
  
  <div class="field">
    <p>user</p>
    <%= f.collection_select :user_id, User.all, :id, :name%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasklists/index.html.erb
<h1>Tasklists#index</h1>
<p>Find me in app/views/tasklists/index.html.erb</p>

<a href='/tasklists/new'>Create new tasklist</a>

<table>
  <tr>
    <td >title</td>
    <td >user</td>
  </tr>
  <% @task_lists.each do |task_list| %>
    <tr>
      <td><%= task_list.title %></td>
      <td><%= link_to "show", tasklist_path(task_list.id)%></td>
    <td><%= link_to "edit", edit_tasklist_path(task_list.id) %> </td>
    <td><%= link_to "destroy", task_list, confirm: "you sure you want to do this?", method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/tasklists/new.html.erb
<h1>Tasklists#new</h1>
<p>Find me in app/views/tasklists/new.html.erb</p>

<%= form_for(@task_list) do |f| %>
  <div class="field">
    <p>title</p>
    <%= f.text_field :title%>
  </div>
  
  <div class="field">
    <p>user</p>
    <%= f.collection_select :user_id, User.all, :id, :name%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasklists/show.html.erb
<div>
  <h2><%= @task_list.title %></h2>
  <p><%= @task_list.user.name unless task_list.user.name.blank? %></p>
</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <p>name</p>
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <p>email</p>
    <%= f.text_field :email%>
  </div>
  <div class="field">
    <p>password</p>
    <%= f.text_field :password%>
  </div>
  
  <div class="actions">
      <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<a href='/users/new'>Create new user</a>

<table>
 	<tr>
 		<td>name</td>
 		<td>email</td>
 		<td>password</td>
 	</tr>
 	<% @users.each do |user| %>
 	<tr>
 		<td><%= user.name %></td>
 		<td><%= user.email %></td>
 		<td><%= user.password %></td>
    <td><%= link_to "show user", user_path(user.id)%></td>
    <td><%= link_to "edit user", edit_user_path(user.id) %> </td>
    <td><%= link_to "destroy user", user, confirm: "you sure you want to do this?", method: :delete %></td>
 	</tr>
 	<% end %>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for(@user) do |f| %>
      <div class="field">
    		<p>name</p> 
    		<%= f.text_field :name%>
    	</div>
    	<div class="field">
    		<p>email</p> 
     		<%= f.text_field :email%>
    	</div>
    	<div class="field">
    		<p>password</p> 
     		<%= f.text_field :password%>
    	</div>
    		<div class="actions">
      		<%= f.submit %>
    	</div>
<% end %>

app/views/users/show.html.erb
<div>
  <h2><%= @user.name %></h2>
  <p><%= @user.email %></p>
  <p><%= @user.password %></p>
</div>

app/views/welcome/index.html.erb
<h1>Hello, Rails! Yichen Wei</h1>
<a href="https://github.com/weyichen/">github.com/weyichen</a>

<form>
<input type="text">
<input type="radio">
<input type="checkbox">
<input type="submit">
</form>

<img border="0" src="http://www.w3schools.com/images/pulpit.jpg" alt="Pulpit rock" width="304" height="228">